version: '2'
services:
  postgreshost:
    image: postgres:latest

  puma_web:
    build: .
    command: sh -c "bundle install && bundle exec puma -C config/puma.rb"
    ports:
      - "3000:3000"
    links:
      - postgreshost
    volumes:
      - /tmp/data-gems/box:/box
      - .:/app

  unicorn_web:
    build: .
    command: sh -c "bundle install && bundle exec unicorn -c config/unicorn.rb"
    ports:
      - "3000:3000"
    links:
      - postgreshost
    volumes:
      - /tmp/data-gems/box:/box
      - .:/app

  tcell_puma_web:
    build: .
    command: sh -c "bundle install && bundle exec puma -C config/puma.rb"
    ports:
      - "3000:3000"
    links:
      - postgreshost
    volumes:
      - /tmp/data-gems/box:/box
      - .:/app
      - ./docker/Gemfile.released:/app/Gemfile

  tcell_unicorn_web:
    build: .
    command: sh -c "bundle install && bundle exec unicorn -c config/unicorn.rb"
    ports:
      - "3000:3000"
    links:
      - postgreshost
    volumes:
      - /tmp/data-gems/box:/box
      - .:/app
      - ./docker/Gemfile.released:/app/Gemfile

  tcell_puma_local_web:
    build: .
    command: sh -c "cd /tcellagent_src && bundle && bundle exec rake compile && cd /app && bundle && bundle exec puma -C config/puma.rb"
    ports:
      - "3000:3000"
    links:
      - postgreshost
    volumes:
      - /tmp/data-gems/box:/box
      - ../rubyagent-tcell/ext:/tcellagent_src/ext
      - ../rubyagent-tcell/lib:/tcellagent_src/lib
      - ../rubyagent-tcell/bin:/tcellagent_src/bin
      - ../rubyagent-tcell/Gemfile:/tcellagent_src/Gemfile
      - ../rubyagent-tcell/Gemfile.lock:/tcellagent_src/Gemfile.lock
      - ../rubyagent-tcell/tcell_agent.gemspec:/tcellagent_src/tcell_agent.gemspec
      - ../rubyagent-tcell/LICENSE:/tcellagent_src/LICENSE
      - ../rubyagent-tcell/Rakefile:/tcellagent_src/Rakefile
      - .:/app
      - ./docker/Gemfile.dev:/app/Gemfile

  tcell_unicorn_local_web:
    build: .
    command: sh -c "cd /tcellagent_src && bundle && bundle exec rake compile && cd /app && bundle && bundle exec unicorn -c config/unicorn.rb"
    ports:
      - "3000:3000"
    links:
      - postgreshost
    volumes:
      - /tmp/data-gems/box:/box
      - ../rubyagent-tcell/ext:/tcellagent_src/ext
      - ../rubyagent-tcell/lib:/tcellagent_src/lib
      - ../rubyagent-tcell/bin:/tcellagent_src/bin
      - ../rubyagent-tcell/Gemfile:/tcellagent_src/Gemfile
      - ../rubyagent-tcell/Gemfile.lock:/tcellagent_src/Gemfile.lock
      - ../rubyagent-tcell/tcell_agent.gemspec:/tcellagent_src/tcell_agent.gemspec
      - ../rubyagent-tcell/LICENSE:/tcellagent_src/LICENSE
      - ../rubyagent-tcell/Rakefile:/tcellagent_src/Rakefile
      - .:/app
      - ./docker/Gemfile.dev:/app/Gemfile

  tcell_passenger_local_web:
    build: .
    command: sh -c "cd /tcellagent_src && bundle && bundle exec rake compile && cd /app && bundle && bundle exec passenger start --max-pool-size 3"
    ports:
      - "3000:3000"
    links:
      - postgreshost
    volumes:
      - /tmp/data-gems/box:/box
      - ../rubyagent-tcell/ext:/tcellagent_src/ext
      - ../rubyagent-tcell/lib:/tcellagent_src/lib
      - ../rubyagent-tcell/bin:/tcellagent_src/bin
      - ../rubyagent-tcell/Gemfile:/tcellagent_src/Gemfile
      - ../rubyagent-tcell/Gemfile.lock:/tcellagent_src/Gemfile.lock
      - ../rubyagent-tcell/tcell_agent.gemspec:/tcellagent_src/tcell_agent.gemspec
      - ../rubyagent-tcell/LICENSE:/tcellagent_src/LICENSE
      - ../rubyagent-tcell/Rakefile:/tcellagent_src/Rakefile
      - .:/app
      - ./docker/Gemfile.dev:/app/Gemfile

  puma_web_ruby23:
    build:
      context: .
      dockerfile: docker/Dockerfile.ruby23
    command: sh -c "bundle install && bundle exec puma -C config/puma.rb"
    ports:
      - "3000:3000"
    links:
      - postgreshost
    volumes:
      - /tmp/data-gems/box23:/box23
      - .:/app

  unicorn_web_ruby23:
    build:
      context: .
      dockerfile: docker/Dockerfile.ruby23
    command: sh -c "bundle install && bundle exec unicorn -c config/unicorn.rb"
    ports:
      - "3000:3000"
    links:
      - postgreshost
    volumes:
      - /tmp/data-gems/box23:/box23
      - .:/app

  passenger_web_ruby23:
    build:
      context: .
      dockerfile: docker/Dockerfile.ruby23
    command: sh -c "bundle install && bundle exec passenger start --max-pool-size 3"
    ports:
      - "3000:3000"
    links:
      - postgreshost
    volumes:
      - /tmp/data-gems/box23:/box23
      - .:/app

  tcell_puma_web_ruby23:
    build:
      context: .
      dockerfile: docker/Dockerfile.ruby23
    command: sh -c "bundle install && bundle exec puma -C config/puma.rb"
    ports:
      - "3000:3000"
    links:
      - postgreshost
    volumes:
      - /tmp/data-gems/box23:/box23
      - .:/app
      - ./docker/Gemfile.released:/app/Gemfile

  tcell_unicorn_web_ruby23:
    build:
      context: .
      dockerfile: docker/Dockerfile.ruby23
    command: sh -c "bundle install && bundle exec unicorn -c config/unicorn.rb"
    ports:
      - "3000:3000"
    links:
      - postgreshost
    volumes:
      - /tmp/data-gems/box23:/box23
      - .:/app
      - ./docker/Gemfile.released:/app/Gemfile

  tcell_passenger_web_ruby23:
    build:
      context: .
      dockerfile: docker/Dockerfile.ruby23
    command: sh -c "bundle install && bundle exec passenger start --max-pool-size 3"
    ports:
      - "3000:3000"
    links:
      - postgreshost
    volumes:
      - /tmp/data-gems/box23:/box23
      - .:/app
      - ./docker/Gemfile.released:/app/Gemfile

  tcell_puma_local_web_ruby23:
    build:
      context: .
      dockerfile: docker/Dockerfile.ruby23
    command: sh -c "cd /tcellagent_src && bundle && bundle exec rake compile && cd /app && bundle && bundle exec puma -C config/puma.rb"
    ports:
      - "3000:3000"
    links:
      - postgreshost
    volumes:
      - /tmp/data-gems/box23:/box23
      - ../rubyagent-tcell/ext:/tcellagent_src/ext
      - ../rubyagent-tcell/lib:/tcellagent_src/lib
      - ../rubyagent-tcell/bin:/tcellagent_src/bin
      - ../rubyagent-tcell/Gemfile:/tcellagent_src/Gemfile
      - ../rubyagent-tcell/Gemfile.lock:/tcellagent_src/Gemfile.lock
      - ../rubyagent-tcell/tcell_agent.gemspec:/tcellagent_src/tcell_agent.gemspec
      - ../rubyagent-tcell/LICENSE:/tcellagent_src/LICENSE
      - ../rubyagent-tcell/Rakefile:/tcellagent_src/Rakefile
      - .:/app
      - ./docker/Gemfile.dev:/app/Gemfile

  tcell_unicorn_local_web_ruby23:
    build:
      context: .
      dockerfile: docker/Dockerfile.ruby23
    command: sh -c "cd /tcellagent_src && bundle && bundle exec rake compile && cd /app && bundle && bundle exec unicorn -c config/unicorn.rb"
    ports:
      - "3000:3000"
    links:
      - postgreshost
    volumes:
      - /tmp/data-gems/box23:/box23
      - ../rubyagent-tcell/ext:/tcellagent_src/ext
      - ../rubyagent-tcell/lib:/tcellagent_src/lib
      - ../rubyagent-tcell/bin:/tcellagent_src/bin
      - ../rubyagent-tcell/Gemfile:/tcellagent_src/Gemfile
      - ../rubyagent-tcell/Gemfile.lock:/tcellagent_src/Gemfile.lock
      - ../rubyagent-tcell/tcell_agent.gemspec:/tcellagent_src/tcell_agent.gemspec
      - ../rubyagent-tcell/LICENSE:/tcellagent_src/LICENSE
      - ../rubyagent-tcell/Rakefile:/tcellagent_src/Rakefile
      - .:/app
      - ./docker/Gemfile.dev:/app/Gemfile

  tcell_passenger_local_web_ruby23:
    build:
      context: .
      dockerfile: docker/Dockerfile.ruby23
    command: sh -c "cd /tcellagent_src && bundle && bundle exec rake compile && cd /app && bundle install && bundle exec passenger start --max-pool-size 3"
    ports:
      - "3000:3000"
    links:
      - postgreshost
    volumes:
      - /tmp/data-gems/box23:/box23
      - ../rubyagent-tcell/ext:/tcellagent_src/ext
      - ../rubyagent-tcell/lib:/tcellagent_src/lib
      - ../rubyagent-tcell/bin:/tcellagent_src/bin
      - ../rubyagent-tcell/Gemfile:/tcellagent_src/Gemfile
      - ../rubyagent-tcell/Gemfile.lock:/tcellagent_src/Gemfile.lock
      - ../rubyagent-tcell/tcell_agent.gemspec:/tcellagent_src/tcell_agent.gemspec
      - ../rubyagent-tcell/LICENSE:/tcellagent_src/LICENSE
      - ../rubyagent-tcell/Rakefile:/tcellagent_src/Rakefile
      - .:/app
      - ./docker/Gemfile.dev:/app/Gemfile
