version: '2'
services:
  db:
    image: postgres:9.4.1
    ports:
      - "5432:5432"

  box:
    image: busybox
    volumes:
      - /box

  puma_web:
    build: .
    command: bundle exec puma -C config/puma.rb
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/rails-waitlist
    volumes_from:
      - box

  unicorn_web:
    build: .
    command: bundle exec unicorn -c config/unicorn.rb
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/rails-waitlist
    volumes_from:
      - box
