version: '2'
services:
  db:
    image: postgres:9.4.1
    ports:
      - "5432:5432"

  box:
    image: busybox
    volumes:
      - /box

  web:
    build: .
    command: bundle exec rails s puma --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/rails-waitlist
    volumes_from:
      - box
